// @ts-check
// This file is automatically generated. DO NOT EDIT

export function ScanProject(arg1:string):Promise<any>;

export function GetNewStrings(arg1:string):Promise<any>;

export function AutoTranslateNewStrings(arg1:string, arg2:string, arg3:string):Promise<any>;