// @ts-check
// This file is automatically generated. DO NOT EDIT

export function ScanProject(arg1) {
  return window['go']['app']['ScannerAPI']['ScanProject'](arg1);
}

export function GetNewStrings(arg1) {
  return window['go']['app']['ScannerAPI']['GetNewStrings'](arg1);
}

export function AutoTranslateNewStrings(arg1, arg2, arg3) {
  return window['go']['app']['ScannerAPI']['AutoTranslateNewStrings'](arg1, arg2, arg3);
}