// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {jobs} from '../models';

export function Greet(arg1:string):Promise<string>;

export function SetRunner(arg1:jobs.Runner):Promise<void>;

export function Version():Promise<string>;

export function SelectProjectFolder(arg1:string):Promise<string>;
