// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetRunner(arg1) {
  return window['go']['main']['App']['SetRunner'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}

export function SelectProjectFolder(arg1) {
  return window['go']['main']['App']['SelectProjectFolder'](arg1);
}
